@BackendAPI_HostAddress = https://localhost:7242

POST {{BackendAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "VeryGoodPassword"
}

###

POST {{BackendAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "example@example.com",
  "password": "VeryGoodPassword"
}

###

POST {{BackendAPI_HostAddress}}/api/game/games
Content-Type: application/json

{
  "name": "CS2",
  "genre": "Ação",
  "description": "Jogo de tiro em primeira pessoa online",
  "releaseDate": "2025-01-01",
  "image": "https://url"
}

###

GET {{BackendAPI_HostAddress}}/api/game/games

###
