@BackendAPI_HostAddress = https://localhost:7242

# ==============================================================================
# USER ENDPOINTS
# ==============================================================================

# @name loginRequest
POST {{BackendAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "VeryGoodPassword"
}

###

POST {{BackendAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "example@example.com",
  "password": "VeryGoodPassword"
}

###

# ==============================================================================
# GAMES ENDPOINTS
# ==============================================================================

GET {{BackendAPI_HostAddress}}/api/game

###

GET {{BackendAPI_HostAddress}}/api/game/5

###

POST {{BackendAPI_HostAddress}}/api/game
Authorization: Bearer {{loginRequest.response.body.$.token}}
Content-Type: application/json

{
  "name": "CS2",
  "genre": "Action",
  "description": "FPS (First Person Shooter) online game",
  "releaseDate": "2025-01-01",
  "image": "https://url"
}

###

DELETE {{BackendAPI_HostAddress}}/api/game/5
Authorization: Bearer {{loginRequest.response.body.$.token}}

###

PUT {{BackendAPI_HostAddress}}/api/game/5
Authorization: Bearer {{loginRequest.response.body.$.token}}
Content-Type: application/json

{
  "id": "5",
  "name": "CS:GO",
  "genre": "Action",
  "description": "FPS (First Person Shooter) online game",
  "releaseDate": "2025-01-01",
  "image": "https://url"
}